[update]
#tasks = ["interfaces", "code", "transform", "normalize"]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
paths = ["iOCNotes", "CloudNotes"]
defaultToBase = true
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePaths = ["iOCNotes", "CloudNotes"]
localizablePath = "."
defaultToKeys = false
additive = true
unstripped = false

[update.transform]
codePath = "."
localizablePath = "."
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
paths = ["iOCNotes", "CloudNotes"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "iOCNotes"
duplicateKeys = true
emptyValues = true
